### INICIO SESION ADMIN
POST http://localhost:7878/login
Content-Type: application/json

{
    "user": "enmarcm",
    "password": "1234567"
}

### PROCESS ADMIN
POST http://localhost:7878/toProcess
Content-Type: application/json

{
    "area": "access",
    "object": "users",
    "method": "seeUser"
}

###INNICIO SESION USER
POST http://localhost:7878/login
Content-Type: application/json

{
    "user": "rafafpf",
    "password": "pass"

}  
### PROCESS USER
POST http://localhost:7878/toProcess
Content-Type: application/json

{
    "area": "access",
    "object": "users",
    "method": "seeUser",
    "params" : ["enmarcm"]
    # Preguntar de cuando pueda usar los parametroscon objeto
}



###SIGUIENTE

POST http://localhost:7878/logout

###CONTENIDO
GET http://localhost:7878/content

###DESBLOQUEO
POST http://localhost:7878/desbloquear
Content-Type: application/json

{
    "user": "enmarcm"
}



###TERCERAS PRUEBAS
POST http://localhost:9923/login
Content-Type: application/json

{
    "user": "enmanuel",
    "password": "enmanuel"
}

###TERCERAS PRUEBAS
GET http://localhost:9923/logout

