### INICIO SESION ADMIN
GET http://localhost:7878/login

###
POST http://localhost:7878/login
Content-Type: application/json

{
    "user": "enmarcm",
    "password": "1234567"
}

###LOGOUT ADMIN
GET http://localhost:7878/logout

### PROCESS ADMIN
POST http://localhost:7878/toProcess
Content-Type: application/json

{
    "area": "access",
    "object": "users",
    "method": "seeUser",
    "params": [{"user": "enmarcm"}]
}


###INICIO SESION USER
POST http://localhost:7878/login
Content-Type: application/json

{
    "user": "rafafpf",
    "password": "pass"

}  
### PROCESS USER
POST http://localhost:7878/toProcess
Content-Type: application/json

{
    "area": "access",
    "object": "users",
    "method": "addUser",
    "params" : [{"user": "migue", "password": "parafraseo", "email": "miguel123@gmail.com",
    "questions" : [{
        "question": "NOMBRE DE TU MAMA",
        "answer": "MARIA"
    }, {
        "question": "NOMBRE DE TU PAPA",
        "answer": "JOSE"
    }, {
        "question": "NOMBRE DE TU ABUELO",
        "answer": "ESTEBAN"
    }
    ]
    }]
}

###SIGUIENTE

POST http://localhost:7878/logout

###CONTENIDO
GET http://localhost:7878/content

###DESBLOQUEO
POST http://localhost:7878/desbloquear
Content-Type: application/json

{
    "user": "enmarcm"
}



###TERCERAS PRUEBAS
POST http://localhost:9923/login
Content-Type: application/json

{
    "user": "enmanuel",
    "password": "enmanuel"
}

###TERCERAS PRUEBAS
GET http://localhost:9923/logout

